package gossip;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hear.proto

public final class HearGossipProto {
  private HearGossipProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface hearGossipRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string msg = 1;
    /**
     * <code>required string msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // required int32 clk = 2;
    /**
     * <code>required int32 clk = 2;</code>
     */
    boolean hasClk();
    /**
     * <code>required int32 clk = 2;</code>
     */
    int getClk();

    // required int32 totalprocess = 3;
    /**
     * <code>required int32 totalprocess = 3;</code>
     */
    boolean hasTotalprocess();
    /**
     * <code>required int32 totalprocess = 3;</code>
     */
    int getTotalprocess();

    // required int32 IDofprocess = 4;
    /**
     * <code>required int32 IDofprocess = 4;</code>
     */
    boolean hasIDofprocess();
    /**
     * <code>required int32 IDofprocess = 4;</code>
     */
    int getIDofprocess();

    // required int32 serverno = 5;
    /**
     * <code>required int32 serverno = 5;</code>
     */
    boolean hasServerno();
    /**
     * <code>required int32 serverno = 5;</code>
     */
    int getServerno();

    // required int32 EventGenerator = 6;
    /**
     * <code>required int32 EventGenerator = 6;</code>
     */
    boolean hasEventGenerator();
    /**
     * <code>required int32 EventGenerator = 6;</code>
     */
    int getEventGenerator();
  }
  /**
   * Protobuf type {@code hearGossipRequest}
   */
  public static final class hearGossipRequest extends
      com.google.protobuf.GeneratedMessage
      implements hearGossipRequestOrBuilder {
    // Use hearGossipRequest.newBuilder() to construct.
    private hearGossipRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private hearGossipRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final hearGossipRequest defaultInstance;
    public static hearGossipRequest getDefaultInstance() {
      return defaultInstance;
    }

    public hearGossipRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private hearGossipRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msg_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clk_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              totalprocess_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              iDofprocess_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              serverno_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              eventGenerator_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HearGossipProto.internal_static_hearGossipRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HearGossipProto.internal_static_hearGossipRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HearGossipProto.hearGossipRequest.class, HearGossipProto.hearGossipRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<hearGossipRequest> PARSER =
        new com.google.protobuf.AbstractParser<hearGossipRequest>() {
      public hearGossipRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new hearGossipRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<hearGossipRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    /**
     * <code>required string msg = 1;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 clk = 2;
    public static final int CLK_FIELD_NUMBER = 2;
    private int clk_;
    /**
     * <code>required int32 clk = 2;</code>
     */
    public boolean hasClk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 clk = 2;</code>
     */
    public int getClk() {
      return clk_;
    }

    // required int32 totalprocess = 3;
    public static final int TOTALPROCESS_FIELD_NUMBER = 3;
    private int totalprocess_;
    /**
     * <code>required int32 totalprocess = 3;</code>
     */
    public boolean hasTotalprocess() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 totalprocess = 3;</code>
     */
    public int getTotalprocess() {
      return totalprocess_;
    }

    // required int32 IDofprocess = 4;
    public static final int IDOFPROCESS_FIELD_NUMBER = 4;
    private int iDofprocess_;
    /**
     * <code>required int32 IDofprocess = 4;</code>
     */
    public boolean hasIDofprocess() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 IDofprocess = 4;</code>
     */
    public int getIDofprocess() {
      return iDofprocess_;
    }

    // required int32 serverno = 5;
    public static final int SERVERNO_FIELD_NUMBER = 5;
    private int serverno_;
    /**
     * <code>required int32 serverno = 5;</code>
     */
    public boolean hasServerno() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 serverno = 5;</code>
     */
    public int getServerno() {
      return serverno_;
    }

    // required int32 EventGenerator = 6;
    public static final int EVENTGENERATOR_FIELD_NUMBER = 6;
    private int eventGenerator_;
    /**
     * <code>required int32 EventGenerator = 6;</code>
     */
    public boolean hasEventGenerator() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 EventGenerator = 6;</code>
     */
    public int getEventGenerator() {
      return eventGenerator_;
    }

    private void initFields() {
      msg_ = "";
      clk_ = 0;
      totalprocess_ = 0;
      iDofprocess_ = 0;
      serverno_ = 0;
      eventGenerator_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalprocess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIDofprocess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerno()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventGenerator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, totalprocess_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, iDofprocess_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, serverno_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, eventGenerator_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalprocess_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, iDofprocess_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, serverno_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, eventGenerator_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static HearGossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HearGossipProto.hearGossipRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HearGossipProto.hearGossipRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HearGossipProto.hearGossipRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HearGossipProto.hearGossipRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hearGossipRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HearGossipProto.hearGossipRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HearGossipProto.internal_static_hearGossipRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HearGossipProto.internal_static_hearGossipRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HearGossipProto.hearGossipRequest.class, HearGossipProto.hearGossipRequest.Builder.class);
      }

      // Construct using HearGossipProto.hearGossipRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clk_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        totalprocess_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        iDofprocess_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverno_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        eventGenerator_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HearGossipProto.internal_static_hearGossipRequest_descriptor;
      }

      public HearGossipProto.hearGossipRequest getDefaultInstanceForType() {
        return HearGossipProto.hearGossipRequest.getDefaultInstance();
      }

      public HearGossipProto.hearGossipRequest build() {
        HearGossipProto.hearGossipRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HearGossipProto.hearGossipRequest buildPartial() {
        HearGossipProto.hearGossipRequest result = new HearGossipProto.hearGossipRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clk_ = clk_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.totalprocess_ = totalprocess_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.iDofprocess_ = iDofprocess_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serverno_ = serverno_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.eventGenerator_ = eventGenerator_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HearGossipProto.hearGossipRequest) {
          return mergeFrom((HearGossipProto.hearGossipRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HearGossipProto.hearGossipRequest other) {
        if (other == HearGossipProto.hearGossipRequest.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          bitField0_ |= 0x00000001;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasClk()) {
          setClk(other.getClk());
        }
        if (other.hasTotalprocess()) {
          setTotalprocess(other.getTotalprocess());
        }
        if (other.hasIDofprocess()) {
          setIDofprocess(other.getIDofprocess());
        }
        if (other.hasServerno()) {
          setServerno(other.getServerno());
        }
        if (other.hasEventGenerator()) {
          setEventGenerator(other.getEventGenerator());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsg()) {
          
          return false;
        }
        if (!hasClk()) {
          
          return false;
        }
        if (!hasTotalprocess()) {
          
          return false;
        }
        if (!hasIDofprocess()) {
          
          return false;
        }
        if (!hasServerno()) {
          
          return false;
        }
        if (!hasEventGenerator()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HearGossipProto.hearGossipRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HearGossipProto.hearGossipRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string msg = 1;
      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }

      // required int32 clk = 2;
      private int clk_ ;
      /**
       * <code>required int32 clk = 2;</code>
       */
      public boolean hasClk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 clk = 2;</code>
       */
      public int getClk() {
        return clk_;
      }
      /**
       * <code>required int32 clk = 2;</code>
       */
      public Builder setClk(int value) {
        bitField0_ |= 0x00000002;
        clk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clk = 2;</code>
       */
      public Builder clearClk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clk_ = 0;
        onChanged();
        return this;
      }

      // required int32 totalprocess = 3;
      private int totalprocess_ ;
      /**
       * <code>required int32 totalprocess = 3;</code>
       */
      public boolean hasTotalprocess() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 totalprocess = 3;</code>
       */
      public int getTotalprocess() {
        return totalprocess_;
      }
      /**
       * <code>required int32 totalprocess = 3;</code>
       */
      public Builder setTotalprocess(int value) {
        bitField0_ |= 0x00000004;
        totalprocess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 totalprocess = 3;</code>
       */
      public Builder clearTotalprocess() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalprocess_ = 0;
        onChanged();
        return this;
      }

      // required int32 IDofprocess = 4;
      private int iDofprocess_ ;
      /**
       * <code>required int32 IDofprocess = 4;</code>
       */
      public boolean hasIDofprocess() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 IDofprocess = 4;</code>
       */
      public int getIDofprocess() {
        return iDofprocess_;
      }
      /**
       * <code>required int32 IDofprocess = 4;</code>
       */
      public Builder setIDofprocess(int value) {
        bitField0_ |= 0x00000008;
        iDofprocess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 IDofprocess = 4;</code>
       */
      public Builder clearIDofprocess() {
        bitField0_ = (bitField0_ & ~0x00000008);
        iDofprocess_ = 0;
        onChanged();
        return this;
      }

      // required int32 serverno = 5;
      private int serverno_ ;
      /**
       * <code>required int32 serverno = 5;</code>
       */
      public boolean hasServerno() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 serverno = 5;</code>
       */
      public int getServerno() {
        return serverno_;
      }
      /**
       * <code>required int32 serverno = 5;</code>
       */
      public Builder setServerno(int value) {
        bitField0_ |= 0x00000010;
        serverno_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverno = 5;</code>
       */
      public Builder clearServerno() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverno_ = 0;
        onChanged();
        return this;
      }

      // required int32 EventGenerator = 6;
      private int eventGenerator_ ;
      /**
       * <code>required int32 EventGenerator = 6;</code>
       */
      public boolean hasEventGenerator() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 EventGenerator = 6;</code>
       */
      public int getEventGenerator() {
        return eventGenerator_;
      }
      /**
       * <code>required int32 EventGenerator = 6;</code>
       */
      public Builder setEventGenerator(int value) {
        bitField0_ |= 0x00000020;
        eventGenerator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 EventGenerator = 6;</code>
       */
      public Builder clearEventGenerator() {
        bitField0_ = (bitField0_ & ~0x00000020);
        eventGenerator_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hearGossipRequest)
    }

    static {
      defaultInstance = new hearGossipRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hearGossipRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearGossipRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearGossipRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhear.proto\"\202\001\n\021hearGossipRequest\022\013\n\003ms" +
      "g\030\001 \002(\t\022\013\n\003clk\030\002 \002(\005\022\024\n\014totalprocess\030\003 \002" +
      "(\005\022\023\n\013IDofprocess\030\004 \002(\005\022\020\n\010serverno\030\005 \002(" +
      "\005\022\026\n\016EventGenerator\030\006 \002(\005B\021B\017HearGossipP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearGossipRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearGossipRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearGossipRequest_descriptor,
              new java.lang.String[] { "Msg", "Clk", "Totalprocess", "IDofprocess", "Serverno", "EventGenerator", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
